// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ALARMS_screen_init(void)
{
ui_ALARMS = lv_obj_create(NULL);
lv_obj_set_scroll_dir(ui_ALARMS, LV_DIR_VER);
lv_obj_set_flex_flow(ui_ALARMS,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ALARMS, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
ui_object_set_themeable_style_property(ui_ALARMS, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_ALARMS, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);

ui_AddAlarm = lv_imgbtn_create(ui_ALARMS);
lv_obj_set_width( ui_AddAlarm, 220);
lv_obj_set_height( ui_AddAlarm, 60);
lv_obj_set_align( ui_AddAlarm, LV_ALIGN_CENTER );
lv_obj_add_state( ui_AddAlarm, LV_STATE_PRESSED );     /// States
lv_obj_add_flag( ui_AddAlarm, LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( ui_AddAlarm, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
ui_object_set_themeable_style_property(ui_AddAlarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_AddAlarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Grey);
lv_obj_set_style_outline_color(ui_AddAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_AddAlarm, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_AddAlarm, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_AddAlarm, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_AddAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_AddAlarm, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_AddAlarm, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_AddAlarm, 1, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImgPanel = lv_obj_create(ui_AddAlarm);
lv_obj_set_width( ui_ImgPanel, 60);
lv_obj_set_height( ui_ImgPanel, 60);
lv_obj_set_align( ui_ImgPanel, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_ImgPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ImgPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_ImgPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_AddAlarmImg = lv_img_create(ui_ImgPanel);
lv_img_set_src(ui_AddAlarmImg, &ui_img_plus32x32_png);
lv_obj_set_width( ui_AddAlarmImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AddAlarmImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AddAlarmImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AddAlarmImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_AddAlarmImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextPanel = lv_obj_create(ui_AddAlarm);
lv_obj_set_width( ui_TextPanel, 165);
lv_obj_set_height( ui_TextPanel, 60);
lv_obj_set_align( ui_TextPanel, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_TextPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_TextPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_TextPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);
lv_obj_set_style_text_color(ui_TextPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AddAlarmText = lv_label_create(ui_TextPanel);
lv_obj_set_width( ui_AddAlarmText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AddAlarmText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AddAlarmText, LV_ALIGN_CENTER );
lv_label_set_text(ui_AddAlarmText,"ADD ALARM");
ui_object_set_themeable_style_property(ui_AddAlarmText, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LightGrey);
ui_object_set_themeable_style_property(ui_AddAlarmText, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LightGrey);
lv_obj_set_style_text_font(ui_AddAlarmText, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_AddAlarm, ui_event_AddAlarm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ALARMS, ui_event_ALARMS, LV_EVENT_ALL, NULL);

}
