// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_BathroomYesNo_screen_init(void)
{
ui_BathroomYesNo = lv_obj_create(NULL);
lv_obj_set_scroll_dir(ui_BathroomYesNo, LV_DIR_HOR);
lv_obj_set_scroll_snap_y(ui_BathroomYesNo, LV_SCROLL_SNAP_START);
lv_obj_set_flex_flow(ui_BathroomYesNo,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_BathroomYesNo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
ui_object_set_themeable_style_property(ui_BathroomYesNo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_BathroomYesNo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);

ui_Label8 = lv_label_create(ui_BathroomYesNo);
lv_obj_set_width( ui_Label8, 230);
lv_obj_set_height( ui_Label8, 70);
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Did your pup use the bathroom?");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFAF6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel17 = lv_obj_create(ui_BathroomYesNo);
lv_obj_set_width( ui_Panel17, 230);
lv_obj_set_height( ui_Panel17, 50);
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Panel17, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_Panel17, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_Checkbox5 = lv_checkbox_create(ui_Panel17);
lv_checkbox_set_text(ui_Checkbox5,"         #1");
lv_obj_set_width( ui_Checkbox5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Checkbox5, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Checkbox5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
ui_object_set_themeable_style_property(ui_Checkbox5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LightGrey);
ui_object_set_themeable_style_property(ui_Checkbox5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LightGrey);
lv_obj_set_style_text_font(ui_Checkbox5, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_Checkbox5, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Checkbox5, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Checkbox5, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Blue);
ui_object_set_themeable_style_property(ui_Checkbox5, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Blue);

ui_Panel18 = lv_obj_create(ui_BathroomYesNo);
lv_obj_set_width( ui_Panel18, 230);
lv_obj_set_height( ui_Panel18, 50);
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Panel18, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_Panel18, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_Checkbox6 = lv_checkbox_create(ui_Panel18);
lv_checkbox_set_text(ui_Checkbox6,"         #2");
lv_obj_set_width( ui_Checkbox6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Checkbox6, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Checkbox6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
ui_object_set_themeable_style_property(ui_Checkbox6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LightGrey);
ui_object_set_themeable_style_property(ui_Checkbox6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LightGrey);
lv_obj_set_style_text_font(ui_Checkbox6, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_Checkbox6, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Checkbox6, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Checkbox6, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Blue);
ui_object_set_themeable_style_property(ui_Checkbox6, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Blue);

ui_Button3 = lv_btn_create(ui_BathroomYesNo);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Continue");

lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BathroomYesNo, ui_event_BathroomYesNo, LV_EVENT_ALL, NULL);

}
