// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_DistanceWalked_screen_init(void)
{
ui_DistanceWalked = lv_obj_create(NULL);
lv_obj_clear_flag( ui_DistanceWalked, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_DistanceWalked, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_DistanceWalked, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);

ui_Label9 = lv_label_create(ui_DistanceWalked);
lv_obj_set_width( ui_Label9, 230);
lv_obj_set_height( ui_Label9, 50);
lv_obj_set_align( ui_Label9, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label9,"How far do you think you walked?");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFBF7F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel19 = lv_obj_create(ui_DistanceWalked);
lv_obj_set_width( ui_Panel19, 230);
lv_obj_set_height( ui_Panel19, 50);
lv_obj_set_x( ui_Panel19, 0 );
lv_obj_set_y( ui_Panel19, -40 );
lv_obj_set_align( ui_Panel19, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel19,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel19, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel19, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Distance_Walked = lv_textarea_create(ui_Panel19);
lv_obj_set_width( ui_Distance_Walked, 120);
lv_obj_set_height( ui_Distance_Walked, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_Distance_Walked, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_Distance_Walked,3);
lv_textarea_set_placeholder_text(ui_Distance_Walked,"0.0");
lv_textarea_set_one_line(ui_Distance_Walked,true);
lv_obj_set_style_text_font(ui_Distance_Walked, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown7 = lv_dropdown_create(ui_Panel19);
lv_dropdown_set_options( ui_Dropdown7, "MI\nKM" );
lv_obj_set_width( ui_Dropdown7, 100);
lv_obj_set_height( ui_Dropdown7, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_Dropdown7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Dropdown7, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_DistanceWalked);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 230);
lv_obj_set_height( ui_Keyboard1, 120);
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_BOTTOM_MID );

lv_keyboard_set_textarea(ui_Keyboard1,ui_Distance_Walked);
lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DistanceWalked, ui_event_DistanceWalked, LV_EVENT_ALL, NULL);

}
