// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_HomeScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HomeScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
ui_object_set_themeable_style_property(ui_HomeScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_HomeScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_pad_row(ui_HomeScreen, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_HomeScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ToAlarms = lv_btn_create(ui_HomeScreen);
lv_obj_set_width( ui_ToAlarms, 100);
lv_obj_set_height( ui_ToAlarms, 50);
lv_obj_set_x( ui_ToAlarms, 0 );
lv_obj_set_y( ui_ToAlarms, 41 );
lv_obj_set_align( ui_ToAlarms, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ToAlarms, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ToAlarms, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeAlarmLabel = lv_label_create(ui_ToAlarms);
lv_obj_set_width( ui_HomeAlarmLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeAlarmLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeAlarmLabel, 0 );
lv_obj_set_y( ui_HomeAlarmLabel, -1 );
lv_obj_set_align( ui_HomeAlarmLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeAlarmLabel,"Alarms");

ui_ToWalkBath = lv_btn_create(ui_HomeScreen);
lv_obj_set_width( ui_ToWalkBath, 100);
lv_obj_set_height( ui_ToWalkBath, 50);
lv_obj_set_align( ui_ToWalkBath, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ToWalkBath, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ToWalkBath, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeWalkLabel = lv_label_create(ui_ToWalkBath);
lv_obj_set_width( ui_HomeWalkLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeWalkLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HomeWalkLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeWalkLabel,"Walk/Bath");

ui_To5SecTimer = lv_btn_create(ui_HomeScreen);
lv_obj_set_width( ui_To5SecTimer, 100);
lv_obj_set_height( ui_To5SecTimer, 50);
lv_obj_set_align( ui_To5SecTimer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_To5SecTimer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_To5SecTimer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimerLabel5Sec = lv_label_create(ui_To5SecTimer);
lv_obj_set_width( ui_TimerLabel5Sec, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimerLabel5Sec, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimerLabel5Sec, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimerLabel5Sec,"5Sec");

lv_obj_add_event_cb(ui_ToAlarms, ui_event_ToAlarms, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ToWalkBath, ui_event_ToWalkBath, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_To5SecTimer, ui_event_To5SecTimer, LV_EVENT_ALL, NULL);

}
