// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MedEditorPage1_screen_init(void)
{
ui_MedEditorPage1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MedEditorPage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_MedEditorPage1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_MedEditorPage1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_AlarmSet2 = lv_obj_create(ui_MedEditorPage1);
lv_obj_remove_style_all(ui_AlarmSet2);
lv_obj_set_width( ui_AlarmSet2, 240);
lv_obj_set_height( ui_AlarmSet2, 280);
lv_obj_set_align( ui_AlarmSet2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_AlarmSet2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_AlarmSet2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_AlarmSet2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_AlarmSet2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_AlarmSet2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InstructionsContainer1 = lv_obj_create(ui_AlarmSet2);
lv_obj_remove_style_all(ui_InstructionsContainer1);
lv_obj_set_width( ui_InstructionsContainer1, 220);
lv_obj_set_height( ui_InstructionsContainer1, 60);
lv_obj_set_align( ui_InstructionsContainer1, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_InstructionsContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InstructionsLabel1 = lv_label_create(ui_InstructionsContainer1);
lv_obj_set_width( ui_InstructionsLabel1, 220);
lv_obj_set_height( ui_InstructionsLabel1, 50);
lv_obj_set_x( ui_InstructionsLabel1, 1 );
lv_obj_set_y( ui_InstructionsLabel1, 5 );
lv_obj_set_align( ui_InstructionsLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_InstructionsLabel1,"Select Medication Category To See Options");
ui_object_set_themeable_style_property(ui_InstructionsLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LightGrey);
ui_object_set_themeable_style_property(ui_InstructionsLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LightGrey);
lv_obj_set_style_text_align(ui_InstructionsLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_medDropdown1 = lv_dropdown_create(ui_AlarmSet2);
lv_dropdown_set_dir( ui_medDropdown1, LV_DIR_TOP);
lv_dropdown_set_options( ui_medDropdown1, "MEDICATION\nANXIETY/DEPRESSION\nNSAID\nANTIBIOTIC\nALLERGY\nPAINKILLER" );
lv_obj_set_width( ui_medDropdown1, 220);
lv_obj_set_height( ui_medDropdown1, 50);
lv_obj_set_x( ui_medDropdown1, 0 );
lv_obj_set_y( ui_medDropdown1, 2 );
lv_obj_set_align( ui_medDropdown1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_medDropdown1, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_medDropdown1, LV_DIR_VER);
lv_obj_set_scroll_snap_x(ui_medDropdown1, LV_SCROLL_SNAP_CENTER);
lv_obj_set_scroll_snap_y(ui_medDropdown1, LV_SCROLL_SNAP_START);
lv_obj_set_style_text_color(ui_medDropdown1, lv_color_hex(0xFBF6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_medDropdown1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_medDropdown1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_medDropdown1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_medDropdown1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_medDropdown1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_allergyMeds = lv_dropdown_create(ui_AlarmSet2);
lv_dropdown_set_dir( ui_allergyMeds, LV_DIR_TOP);
lv_dropdown_set_options( ui_allergyMeds, "ALLERGY\nAPOQUEL\nBENADRYL\nCLARiTIN\nZYRTEC\nALLEGRA" );
lv_obj_set_width( ui_allergyMeds, 220);
lv_obj_set_height( ui_allergyMeds, 50);
lv_obj_set_x( ui_allergyMeds, 0 );
lv_obj_set_y( ui_allergyMeds, 2 );
lv_obj_set_align( ui_allergyMeds, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_allergyMeds, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_allergyMeds, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_allergyMeds, LV_DIR_VER);
lv_obj_set_scroll_snap_x(ui_allergyMeds, LV_SCROLL_SNAP_CENTER);
lv_obj_set_scroll_snap_y(ui_allergyMeds, LV_SCROLL_SNAP_START);
lv_obj_set_style_text_color(ui_allergyMeds, lv_color_hex(0xFBF6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_allergyMeds, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_allergyMeds, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_allergyMeds, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_allergyMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_allergyMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_antibioticMeds = lv_dropdown_create(ui_AlarmSet2);
lv_dropdown_set_dir( ui_antibioticMeds, LV_DIR_TOP);
lv_dropdown_set_options( ui_antibioticMeds, "ANTIBIOTIC\nBAYTRIL\nORBEX\nZENIQUIN\nAMOXICILLIN\nCEPHALEXIN" );
lv_obj_set_width( ui_antibioticMeds, 220);
lv_obj_set_height( ui_antibioticMeds, 50);
lv_obj_set_x( ui_antibioticMeds, 0 );
lv_obj_set_y( ui_antibioticMeds, 2 );
lv_obj_set_align( ui_antibioticMeds, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_antibioticMeds, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_antibioticMeds, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_antibioticMeds, LV_DIR_VER);
lv_obj_set_scroll_snap_x(ui_antibioticMeds, LV_SCROLL_SNAP_CENTER);
lv_obj_set_scroll_snap_y(ui_antibioticMeds, LV_SCROLL_SNAP_START);
lv_obj_set_style_text_color(ui_antibioticMeds, lv_color_hex(0xFBF6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_antibioticMeds, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_antibioticMeds, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_antibioticMeds, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_antibioticMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_antibioticMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_anxietyMeds = lv_dropdown_create(ui_AlarmSet2);
lv_dropdown_set_dir( ui_anxietyMeds, LV_DIR_TOP);
lv_dropdown_set_options( ui_anxietyMeds, "ANXIETY\nALPRAZOLAM\nAMITRIPTYLINE\nBUSPIRONE" );
lv_obj_set_width( ui_anxietyMeds, 220);
lv_obj_set_height( ui_anxietyMeds, 50);
lv_obj_set_x( ui_anxietyMeds, 0 );
lv_obj_set_y( ui_anxietyMeds, 2 );
lv_obj_set_align( ui_anxietyMeds, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_anxietyMeds, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_anxietyMeds, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_anxietyMeds, LV_DIR_VER);
lv_obj_set_scroll_snap_x(ui_anxietyMeds, LV_SCROLL_SNAP_CENTER);
lv_obj_set_scroll_snap_y(ui_anxietyMeds, LV_SCROLL_SNAP_START);
lv_obj_set_style_text_color(ui_anxietyMeds, lv_color_hex(0xFBF6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_anxietyMeds, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_anxietyMeds, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_anxietyMeds, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_anxietyMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_anxietyMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_painMeds = lv_dropdown_create(ui_AlarmSet2);
lv_dropdown_set_dir( ui_painMeds, LV_DIR_TOP);
lv_dropdown_set_options( ui_painMeds, "PAINKILLER\nCARPROFEN\nMELOXICAM\nDERACOXIB\nGABAPENTIN\nAMITRIPTYLINE" );
lv_obj_set_width( ui_painMeds, 220);
lv_obj_set_height( ui_painMeds, 50);
lv_obj_set_x( ui_painMeds, 0 );
lv_obj_set_y( ui_painMeds, 2 );
lv_obj_set_align( ui_painMeds, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_painMeds, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_painMeds, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_painMeds, LV_DIR_VER);
lv_obj_set_scroll_snap_x(ui_painMeds, LV_SCROLL_SNAP_CENTER);
lv_obj_set_scroll_snap_y(ui_painMeds, LV_SCROLL_SNAP_START);
lv_obj_set_style_text_color(ui_painMeds, lv_color_hex(0xFBF6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_painMeds, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_painMeds, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_painMeds, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_painMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_painMeds, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_submit2 = lv_btn_create(ui_AlarmSet2);
lv_obj_set_width( ui_submit2, 100);
lv_obj_set_height( ui_submit2, 50);
lv_obj_set_x( ui_submit2, 0 );
lv_obj_set_y( ui_submit2, 60 );
lv_obj_set_align( ui_submit2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_submit2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_submit2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SubmitText1 = lv_label_create(ui_submit2);
lv_obj_set_width( ui_SubmitText1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubmitText1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SubmitText1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubmitText1,"Save");
lv_obj_set_style_text_font(ui_SubmitText1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SubmitText1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SubmitText1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_medDropdown1, ui_event_medDropdown1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_submit2, ui_event_submit2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MedEditorPage1, ui_event_MedEditorPage1, LV_EVENT_ALL, NULL);

}
