// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_NewAlarm_screen_init(void)
{
ui_NewAlarm = lv_obj_create(NULL);
lv_obj_clear_flag( ui_NewAlarm, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
ui_object_set_themeable_style_property(ui_NewAlarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_NewAlarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);

ui_AlarmSet1 = lv_obj_create(ui_NewAlarm);
lv_obj_remove_style_all(ui_AlarmSet1);
lv_obj_set_width( ui_AlarmSet1, 240);
lv_obj_set_height( ui_AlarmSet1, 280);
lv_obj_set_align( ui_AlarmSet1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_AlarmSet1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_AlarmSet1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_AlarmSet1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_AlarmSet1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_AlarmSet1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlarmTime3 = lv_obj_create(ui_AlarmSet1);
lv_obj_set_width( ui_AlarmTime3, 230);
lv_obj_set_height( ui_AlarmTime3, 90);
lv_obj_set_x( ui_AlarmTime3, 0 );
lv_obj_set_y( ui_AlarmTime3, 40 );
lv_obj_set_align( ui_AlarmTime3, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_AlarmTime3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_AlarmTime3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_AlarmTime3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_HourRoller4 = lv_roller_create(ui_AlarmTime3);
lv_roller_set_options( ui_HourRoller4, "12\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_HourRoller4, 80);
lv_obj_set_height( ui_HourRoller4, 80);
lv_obj_set_align( ui_HourRoller4, LV_ALIGN_LEFT_MID );
lv_obj_add_state( ui_HourRoller4, LV_STATE_FOCUSED );     /// States
lv_obj_set_style_text_color(ui_HourRoller4, lv_color_hex(0xEBC32B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HourRoller4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HourRoller4, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_LightGrey);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_LightGrey);
lv_obj_set_style_border_width(ui_HourRoller4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Blue);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Blue);

lv_obj_set_style_text_color(ui_HourRoller4, lv_color_hex(0xEBC32B), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HourRoller4, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_HourRoller4, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_Label3 = lv_label_create(ui_AlarmTime3);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,":");
lv_obj_clear_flag( ui_Label3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_LightGrey);
ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_LightGrey);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinRoller = lv_roller_create(ui_AlarmTime3);
lv_roller_set_options( ui_MinRoller, "00\n05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_MinRoller, 80);
lv_obj_set_height( ui_MinRoller, 80);
lv_obj_set_align( ui_MinRoller, LV_ALIGN_RIGHT_MID );
lv_obj_add_state( ui_MinRoller, LV_STATE_FOCUSED );     /// States
lv_obj_set_style_text_color(ui_MinRoller, lv_color_hex(0xEBC32B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinRoller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MinRoller, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_LightGrey);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_LightGrey);
lv_obj_set_style_border_width(ui_MinRoller, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Blue);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Blue);

lv_obj_set_style_text_color(ui_MinRoller, lv_color_hex(0xEBC32B), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinRoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_MinRoller, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);

ui_AMPMToggle = lv_btn_create(ui_AlarmSet1);
lv_obj_set_width( ui_AMPMToggle, 100);
lv_obj_set_height( ui_AMPMToggle, 50);
lv_obj_set_align( ui_AMPMToggle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AMPMToggle, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AMPMToggle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_AMPMToggle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_AMPMToggle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);

ui_AMToggleLabel = lv_label_create(ui_AMPMToggle);
lv_obj_set_width( ui_AMToggleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AMToggleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AMToggleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AMToggleLabel,"AM");
lv_obj_add_flag( ui_AMToggleLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_AMToggleLabel, lv_color_hex(0xEBC32B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AMToggleLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AMToggleLabel, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PMToggleLabel = lv_label_create(ui_AMPMToggle);
lv_obj_set_width( ui_PMToggleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PMToggleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PMToggleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PMToggleLabel,"PM");
lv_obj_set_style_text_color(ui_PMToggleLabel, lv_color_hex(0xEBC32B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PMToggleLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PMToggleLabel, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PMToggleLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_PMToggleLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);

ui_submit1 = lv_btn_create(ui_AlarmSet1);
lv_obj_set_width( ui_submit1, 100);
lv_obj_set_height( ui_submit1, 50);
lv_obj_set_x( ui_submit1, 0 );
lv_obj_set_y( ui_submit1, 60 );
lv_obj_set_align( ui_submit1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_submit1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_submit1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SubmitText = lv_label_create(ui_submit1);
lv_obj_set_width( ui_SubmitText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubmitText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SubmitText, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubmitText,"ADD");
lv_obj_set_style_text_font(ui_SubmitText, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_AMPMToggle, ui_event_AMPMToggle, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_submit1, ui_event_submit1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_NewAlarm, ui_event_NewAlarm, LV_EVENT_ALL, NULL);

}
