// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t *ui_HomeScreen;
void ui_event_ToAlarms( lv_event_t * e);
lv_obj_t *ui_ToAlarms;
lv_obj_t *ui_HomeAlarmLabel;
void ui_event_ToWalkBath( lv_event_t * e);
lv_obj_t *ui_ToWalkBath;
lv_obj_t *ui_HomeWalkLabel;
void ui_event_To5SecTimer( lv_event_t * e);
lv_obj_t *ui_To5SecTimer;
lv_obj_t *ui_TimerLabel5Sec;
// CUSTOM VARIABLES

// SCREEN: ui_ALARMS
void ui_ALARMS_screen_init(void);
void ui_event_ALARMS( lv_event_t * e);
lv_obj_t *ui_ALARMS;
void ui_event_AddAlarm( lv_event_t * e);
lv_obj_t *ui_AddAlarm;
lv_obj_t *ui_ImgPanel;
lv_obj_t *ui_AddAlarmImg;
lv_obj_t *ui_TextPanel;
lv_obj_t *ui_AddAlarmText;
// CUSTOM VARIABLES

// SCREEN: ui_NewAlarm
void ui_NewAlarm_screen_init(void);
void ui_event_NewAlarm( lv_event_t * e);
lv_obj_t *ui_NewAlarm;
lv_obj_t *ui_AlarmSet1;
lv_obj_t *ui_AlarmTime3;
lv_obj_t *ui_HourRoller4;
lv_obj_t *ui_Label3;
lv_obj_t *ui_MinRoller;
void ui_event_AMPMToggle( lv_event_t * e);
lv_obj_t *ui_AMPMToggle;
lv_obj_t *ui_AMToggleLabel;
lv_obj_t *ui_PMToggleLabel;
void ui_event_submit1( lv_event_t * e);
lv_obj_t *ui_submit1;
lv_obj_t *ui_SubmitText;
// CUSTOM VARIABLES

// SCREEN: ui_MedEditorPage1
void ui_MedEditorPage1_screen_init(void);
void ui_event_MedEditorPage1( lv_event_t * e);
lv_obj_t *ui_MedEditorPage1;
lv_obj_t *ui_AlarmSet2;
lv_obj_t *ui_InstructionsContainer1;
lv_obj_t *ui_InstructionsLabel1;
void ui_event_medDropdown1( lv_event_t * e);
lv_obj_t *ui_medDropdown1;
lv_obj_t *ui_allergyMeds;
lv_obj_t *ui_antibioticMeds;
lv_obj_t *ui_anxietyMeds;
lv_obj_t *ui_painMeds;
void ui_event_submit2( lv_event_t * e);
lv_obj_t *ui_submit2;
lv_obj_t *ui_SubmitText1;
// CUSTOM VARIABLES

// SCREEN: ui_BathroomYesNo
void ui_BathroomYesNo_screen_init(void);
void ui_event_BathroomYesNo( lv_event_t * e);
lv_obj_t *ui_BathroomYesNo;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Panel17;
lv_obj_t *ui_Checkbox5;
lv_obj_t *ui_Panel18;
lv_obj_t *ui_Checkbox6;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label13;
// CUSTOM VARIABLES

// SCREEN: ui_DistanceWalked
void ui_DistanceWalked_screen_init(void);
void ui_event_DistanceWalked( lv_event_t * e);
lv_obj_t *ui_DistanceWalked;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Panel19;
lv_obj_t *ui_Distance_Walked;
lv_obj_t *ui_Dropdown7;
void ui_event_Keyboard1( lv_event_t * e);
lv_obj_t *ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_EditNewAlarm
void ui_EditNewAlarm_screen_init(void);
void ui_event_EditNewAlarm( lv_event_t * e);
lv_obj_t *ui_EditNewAlarm;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Button7;
lv_obj_t *ui_Label17;
lv_obj_t *ui_AlarmTimeTextArea;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_TextArea1;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label4;
lv_obj_t *ui_TextArea2;
lv_obj_t *ui_Button6;
lv_obj_t *ui_Switch2;
lv_obj_t *ui_TextArea4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ToAlarms( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ALARMS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ALARMS_screen_init);
}
}

void ui_event_ToWalkBath( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_BathroomYesNo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BathroomYesNo_screen_init);
}
}

void ui_event_To5SecTimer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      start_timer_5s( e );
}
}

void ui_event_ALARMS( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
}
}

void ui_event_AddAlarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_NewAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_NewAlarm_screen_init);
}
}

void ui_event_NewAlarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ALARMS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ALARMS_screen_init);
}
}

void ui_event_AMPMToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_AMToggleLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
      _ui_flag_modify( ui_PMToggleLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

void ui_event_submit1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      AlarmAddedESP( e );
      _ui_screen_change( &ui_EditNewAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_EditNewAlarm_screen_init);
}
}

void ui_event_MedEditorPage1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ALARMS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ALARMS_screen_init);
}
}

void ui_event_medDropdown1(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED) {
        lv_obj_t * dropdown = lv_event_get_target(e);

        // Get selected category string
        char selected[32];
        lv_dropdown_get_selected_str(dropdown, selected, sizeof(selected));

        // Hide all med dropdowns first
        lv_obj_add_flag(ui_allergyMeds, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_antibioticMeds, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_anxietyMeds, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_painMeds, LV_OBJ_FLAG_HIDDEN);

        // Unhide the one that matches the selected category
        if (strcmp(selected, "ALLERGY") == 0) {
            lv_obj_clear_flag(ui_allergyMeds, LV_OBJ_FLAG_HIDDEN);
        } else if (strcmp(selected, "ANTIBIOTIC") == 0) {
            lv_obj_clear_flag(ui_antibioticMeds, LV_OBJ_FLAG_HIDDEN);
        } else if (strcmp(selected, "ANXIETY") == 0) {
            lv_obj_clear_flag(ui_anxietyMeds, LV_OBJ_FLAG_HIDDEN);
        } else if (strcmp(selected, "PAIN") == 0) {
            lv_obj_clear_flag(ui_painMeds, LV_OBJ_FLAG_HIDDEN);
        }
    }
}


void ui_event_submit2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      medsAdded( e );
}
}

void ui_event_BathroomYesNo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_DistanceWalked, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DistanceWalked_screen_init);
}
}

void ui_event_DistanceWalked( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_BathroomYesNo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BathroomYesNo_screen_init);
}
}

void ui_event_Keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER  ) {
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
}
}

void ui_event_EditNewAlarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ALARMS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ALARMS_screen_init);
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MedEditorPage1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MedEditorPage1_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_HomeScreen_screen_init();
ui_ALARMS_screen_init();
ui_NewAlarm_screen_init();
ui_MedEditorPage1_screen_init();
ui_BathroomYesNo_screen_init();
ui_DistanceWalked_screen_init();
ui_EditNewAlarm_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_HomeScreen);
}
