// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t *ui_HomeScreen;
void ui_event_ToAlarms( lv_event_t * e);
extern lv_obj_t *ui_ToAlarms;
extern lv_obj_t *ui_HomeAlarmLabel;
void ui_event_ToWalkBath( lv_event_t * e);
extern lv_obj_t *ui_ToWalkBath;
extern lv_obj_t *ui_HomeWalkLabel;
void ui_event_To5SecTimer( lv_event_t * e);
extern lv_obj_t *ui_To5SecTimer;
extern lv_obj_t *ui_TimerLabel5Sec;
// CUSTOM VARIABLES

// SCREEN: ui_ALARMS
void ui_ALARMS_screen_init(void);
void ui_event_ALARMS( lv_event_t * e);
extern lv_obj_t *ui_ALARMS;
void ui_event_AddAlarm( lv_event_t * e);
extern lv_obj_t *ui_AddAlarm;
extern lv_obj_t *ui_ImgPanel;
extern lv_obj_t *ui_AddAlarmImg;
extern lv_obj_t *ui_TextPanel;
extern lv_obj_t *ui_AddAlarmText;
// CUSTOM VARIABLES

// SCREEN: ui_NewAlarm
void ui_NewAlarm_screen_init(void);
void ui_event_NewAlarm( lv_event_t * e);
extern lv_obj_t *ui_NewAlarm;
extern lv_obj_t *ui_AlarmSet1;
extern lv_obj_t *ui_AlarmTime3;
extern lv_obj_t *ui_HourRoller4;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_MinRoller;
void ui_event_AMPMToggle( lv_event_t * e);
extern lv_obj_t *ui_AMPMToggle;
extern lv_obj_t *ui_AMToggleLabel;
extern lv_obj_t *ui_PMToggleLabel;
void ui_event_submit1( lv_event_t * e);
extern lv_obj_t *ui_submit1;
extern lv_obj_t *ui_SubmitText;
// CUSTOM VARIABLES

// SCREEN: ui_MedEditorPage1
void ui_MedEditorPage1_screen_init(void);
void ui_event_MedEditorPage1( lv_event_t * e);
extern lv_obj_t *ui_MedEditorPage1;
extern lv_obj_t *ui_AlarmSet2;
extern lv_obj_t *ui_InstructionsContainer1;
extern lv_obj_t *ui_InstructionsLabel1;
void ui_event_medDropdown1( lv_event_t * e);
extern lv_obj_t *ui_medDropdown1;
extern lv_obj_t *ui_allergyMeds;
extern lv_obj_t *ui_antibioticMeds;
extern lv_obj_t *ui_anxietyMeds;
extern lv_obj_t *ui_painMeds;
void ui_event_submit2( lv_event_t * e);
extern lv_obj_t *ui_submit2;
extern lv_obj_t *ui_SubmitText1;
// CUSTOM VARIABLES

// SCREEN: ui_BathroomYesNo
void ui_BathroomYesNo_screen_init(void);
void ui_event_BathroomYesNo( lv_event_t * e);
extern lv_obj_t *ui_BathroomYesNo;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Checkbox5;
extern lv_obj_t *ui_Panel18;
extern lv_obj_t *ui_Checkbox6;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label13;
// CUSTOM VARIABLES

// SCREEN: ui_DistanceWalked
void ui_DistanceWalked_screen_init(void);
void ui_event_DistanceWalked( lv_event_t * e);
extern lv_obj_t *ui_DistanceWalked;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Panel19;
extern lv_obj_t *ui_Distance_Walked;
extern lv_obj_t *ui_Dropdown7;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_EditNewAlarm
void ui_EditNewAlarm_screen_init(void);
void ui_event_EditNewAlarm( lv_event_t * e);
extern lv_obj_t *ui_EditNewAlarm;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_AlarmTimeTextArea;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_TextArea1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_TextArea4;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_plus32x32_png);   // assets/Plus32x32.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
