// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ESPCollar

#ifndef _ESPCOLLAR_UI_H
#define _ESPCOLLAR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_InfoTab;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_MedsTab;
extern lv_obj_t *ui_Roller1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_ApptsTab;
extern lv_obj_t *ui_Calendar1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
