// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "../rtc/rtc_timer.h"
void alarmAdded(lv_event_t * e)
{
	// Your code here
}

void AlarmAdded(lv_event_t * e)
{
	// Your code here
}

void medsAdded(lv_event_t * e)
{
	// Your code here
}

void start_timer_5s(lv_event_t * e)
{
	start_rtc_timer(5);
}

void AlarmAddedESP(lv_event_t * e)
{
	// Your code here
}
