// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Black[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_Black[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Blue[2] = {0x0A95EE, 0x0A95EE};
const ui_theme_variable_t _ui_theme_alpha_Blue[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Red[2] = {0xDC1922, 0xDC1922};
const ui_theme_variable_t _ui_theme_alpha_Red[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Grey[2] = {0x433F3F, 0x433F3F};
const ui_theme_variable_t _ui_theme_alpha_Grey[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_LightGrey[2] = {0x959090, 0x959090};
const ui_theme_variable_t _ui_theme_alpha_LightGrey[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DARKMODE;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

